### ISSUE TITLE
{"content": "No JSON detected, did you set the Content-Type to application/json?", "success": false}

### ISSUE THREAD

**Issue by fatgit** [zorkian/nagios-api#61]
I try
curl -d '{"host": "localhost", "duration": 600}'       http://localhost:8080/schedule_downtime
and my result
{"content": "No JSON detected, did you set the Content-Type to application/json?", "success": false}
what am I doing wrong?

**Comment by fatgit** [comment]
I got it. Works fine
curl -H "Content-Type: application/json" -d '{"host": "localhost", "duration": 600}'   http://localhost:8080/schedule_downtime

**Comment by zorkian** [comment]
Great Glad you got it! :)
