### ISSUE TITLE
README as Markdown file

### ISSUE THREAD

**Issue by fallais** [zorkian/nagios-api#67]
Hello,

You should set the README file as a Markdown one : README.md
So that the display can be nice.

Regards.

**Comment by mrcrilly** [comment]
A simple pull request should resolve this.

**Comment by ketheriel** [comment]
The display can be nice where?

cat /usr/share/doc/nagios-api/README.md

that for sure looks nice for any system administrator to read the file 👍

**Comment by kwaping** [comment]
Moving README to README.md is nicer for GitHub display, but it breaks RPM building with setup.py. I have a pull request in progress to address this.

**Comment by lollipopman** [comment]
This was done, can we close this issue?
