### ISSUE TITLE
Dependencies question

### ISSUE THREAD

**Issue by kwaping** [zorkian/nagios-api#86]
Hi Mark, first of all thank you for creating this great piece of software. You will have a PR coming from me in the future. On to my question...

What is the reason for the greenlet dependency being locked to version 0.3.4? 0.4.12 is latest. If your software can work with >=0.3.4 that might be better for everyone.

Thanks!

**Comment by zorkian** [comment]
I don't know of a particular reason. Is there a reason to upgrade?
Usually upgrading dependencies requires testing and validation that
everything still works. If you're willing to put in the time for that
then that would be fine.

**Comment by kwaping** [comment]
Noted, I'll see what I can do about that. Thanks!
